---
services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
      #security_opt:
      #- seccomp=unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./config:/config
      - /mnt/RAID/public/eBooks:/mnt/eBooks
    restart: unless-stopped

networks:
  default:
    external: true
    name: calibre
